version: "3.9"
services:
  redpanda-1:
    image: redpandadata/redpanda:v24.2.18
    container_name: redpanda-1
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '1'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda-1:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda-1:28082,OUTSIDE://localhost:8082
      - --rpc-addr
      - 0.0.0.0:33145
      - --advertise-rpc-addr
      - redpanda-1:33145
    ports:
      # - 8081:8081
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092

  jobmanager:
    build:
      context: .
      dockerfile: ./Dockerfile.flink
    image: pyflink:1.16.0
    container_name: "flink-jobmanager"
    pull_policy: never
    platform: "linux/amd64"
    hostname: "jobmanager"
    expose:
      - "6123"
    ports:
      - "8081:8081"
    volumes:
      - ./:/opt/flink/usrlib
      - ./keys/:/var/private/ssl/
      - ./src/:/opt/src
    command: jobmanager 
    extra_hosts:
      - "host.docker.internal:127.0.0.1" #// Linux
      - "host.docker.internal:host-gateway" #// Access services on the host machine from within the Docker container
    environment:
      - POSTGRES_URL=${POSTGRES_URL:-jdbc:postgresql://host.docker.internal:5432/postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        
  
  # Flink task manager
  taskmanager:
    image: pyflink:1.16.0
    container_name: "flink-taskmanager"
    pull_policy: never
    platform: "linux/amd64"
    expose:
      - "6121"
      - "6122"
    volumes:
      - ./:/opt/flink/usrlib
      - ./src/:/opt/src
    depends_on:
      - jobmanager
    command: taskmanager --taskmanager.registration.timeout 5 min
    extra_hosts:
      - "host.docker.internal:127.0.0.1" #// Linux
      - "host.docker.internal:host-gateway" #// Access services on the host machine from within the Docker container
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 15
        parallelism.default: 3
  postgres:
    image: postgres:14
    restart: on-failure
    container_name: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    extra_hosts:
     - "host.docker.internal:127.0.0.1" #// Linux
     - "host.docker.internal:host-gateway" #// Access services on the host machine from within the Docker container

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - redpanda-1
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: redpanda-1:29092

  # ####################
  # # Redpanda Console #
  # ####################
  # console:
  #   container_name: redpanda-console
  #   image: docker.redpanda.com/redpandadata/console:v2.8.4
  #   # networks:
  #   #   - redpanda_network
  #   entrypoint: /bin/sh
  #   command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml && echo "$$CONSOLE_ROLEBINDINGS_CONFIG_FILE" > /tmp/role-bindings.yml && /app/console'
  #   volumes:
  #     - ./config:/tmp/config/
  #   environment:
  #     CONFIG_FILEPATH: ${CONFIG_FILEPATH:-/tmp/config.yml}
  #     CONSOLE_CONFIG_FILE: |
  #       # Configure a connection to the Redpanda cluster
  #       # See https://docs.redpanda.com/current/console/config/connect-to-redpanda/
  #       kafka:
  #         brokers: ["redpanda-1:9092"]
  #         # schemaRegistry:
  #         #   enabled: true
  #         #   urls: ["http://redpanda-0:8081","http://redpanda-1:8081","http://redpanda-2:8081"]
  #         # sasl:
  #         #   enabled: true
  #         #   username: superuser
  #         #   password: secretpassword
  #         #   mechanism: SCRAM-SHA-256
  #       # redpanda:
  #       #   adminApi:
  #       #     enabled: true
  #       #     urls: ["http://redpanda-0:9644","http://redpanda-1:9644","http://redpanda-2:9644"]
  #       #     username: superuser
  #       #     password: secretpassword
  #       console:
  #         # Configures Redpanda Console to fetch topic documentation from GitHub and display it in the UI.
  #         # See https://docs.redpanda.com/current/console/config/topic-documentation/
  #         topicDocumentation:
  #           enabled: true
  #           git:
  #             enabled: true
  #             repository:
  #               url: https://github.com/redpanda-data/docs
  #               branch: main
  #               baseDirectory: tests/docker-compose
  #       login:
  #         enabled: true
  #         jwtSecret: change-this-to-something-secret
  #         useSecureCookies: false
  #         # Enable plain login authentication (enterprise feature)
  #         # See https://docs.redpanda.com/current/console/config/security/plain/
  #         plain:
  #           enabled: true
  #           credentials:
  #           - username: "jane"
  #             password: "some-other-secret-password"
  #           - username: "john"
  #             password: "some-secret-password"
  #       enterprise:
  #         # Configures role-based access control to data and features in Redpanda Console.
  #         # See https://docs.redpanda.com/current/console/config/security/authorization/
  #         rbac:
  #           enabled: true
  #           roleBindingsFilepath: /tmp/role-bindings.yml
  #     CONSOLE_ROLEBINDINGS_CONFIG_FILE: |
  #       roleBindings:
  #       - metadata:
  #           name: Platform Ops
  #         subjects:
  #           - kind: user
  #             provider: Plain
  #             name: jane
  #         roleName: admin
  #       - metadata:
  #           name: Software Engineers
  #         subjects:
  #           - kind: user
  #             provider: Plain
  #             name: john
  #         roleName: editor
  #   ports:
  #     - 8080:8080
  #   # depends_on:
  #   #   redpanda-1:
  #   #     condition: service_healthy